### ISSUE TITLE
GROMACS/LSDMap Analysis step fails on Stampede

### ISSUE THREAD

**Issue by CharlieLaughton** [radical-cybertools/ExTASY#143] opened 2015-02-05 09:57 UTC
Unfortunately #141 does not seem fixed.

I have updated:
```
[ExTASY-tools] [d-156-140-6:~/grlasd-on-stampede] charlie% python -c 'import radical.ensemblemd.extasy as extasy; print extasy.version'
0.1.1-beta-1-g41a7bb8
[ExTASY-tools] [d-156-140-6:~/grlasd-on-stampede] charlie% 
```

But stil get:

```
...
[Callback]: ComputeUnit '54d33cee95f3d013787567b0' state changed to Done.
[Callback]: ComputeUnit '54d33cee95f3d013787567ad' state changed to Done.
Simulation Execution Time :  59.614
Starting Analysis
[Callback]: ComputeUnit '54d33d2b95f3d013787567b1' state changed to PendingExecution.
[Callback]: ComputeUnit '54d33d2b95f3d013787567b1' state changed to Scheduling.
[Callback]: ComputeUnit '54d33d2b95f3d013787567b1' state changed to Executing.
[Callback]: ComputeUnit '54d33d2b95f3d013787567b1' state changed to Failed.
#######################
##       ERROR       ##
#######################
ComputeUnit 54d33d2b95f3d013787567b1 has FAILED. Can't recover.
ComputeUnit log: [<radical.pilot.logentry.Logentry object at 0x1064c6a10>]
Select + Reweighting step
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/Users/charlie/ExTASY-tools/lib/python2.7/site-packages/radical/pilot/controller/unit_manager_controller.py", line 302, in run
    self.call_unit_state_callbacks(unit_id, new_state)
  File "/Users/charlie/ExTASY-tools/lib/python2.7/site-packages/radical/pilot/controller/unit_manager_controller.py", line 202, in call_unit_state_callbacks
    cb(self._shared_data[unit_id]['facade_object'], new_state)
  File "/Users/charlie/ExTASY-tools/lib/python2.7/site-packages/radical/ensemblemd/extasy/bin/runme.py", line 52, in unit_state_change_cb
    print u"STDERR : {0}".format(unit.stderr)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 310: ordinal not in range(128)

^CExecution was interrupted
Closing session, exiting now ...
[Callback]: ComputePilot '54d33c4895f3d0137875679e' state changed to Canceled.
```

**Comment by vivek-bala** [comment] 2015-02-20 19:08
Closing this, duplicate of #141 .

**Closed by vivek-bala** 2015-02-20 19:08 UTC
