### ISSUE TITLE
Failure of Amber/CoCo on Stampede from Notts linux workstations when numIterations = 9

### ISSUE THREAD

**Issue by ashkurti** [radical-cybertools/ExTASY#137] opened 2015-01-05 12:06 UTC
Extasy log at: https://gist.github.com/ashkurti/fdbc29a90ddd03421cbf

**Comment by ashkurti** [comment] 2015-01-05 12:21
Just need to add that, the back-up folder has been created but containing only info on iter2 and iter4.

**Comment by oleweidner** [comment] 2015-01-05 14:35
Closing this as a duplicate of https://github.com/radical-cybertools/ExTASY/issues/135. 

Ardita - are you using the latest versions of all tools?

**Comment by ashkurti** [comment] 2015-01-05 16:22
@oleweidner yes, I have been using the latest versions of all tools.

**Comment by vivek-bala** [comment] 2015-01-05 16:28
The job fails during execution with an mpi error but the agent seems to encounter system exit much before that in line https://gist.github.com/ashkurti/fdbc29a90ddd03421cbf#file-gistfile1-txt-L5351. Could this be the reason, the unit fails. @andre-merzky any insight as to why this might happen ?

**Comment by andre-merzky** [comment] 2015-01-05 16:56
My hunch would be that a unit state callback calls `sys.exit()` on a `FAILED` unit, thus creating the, aehm, system exit condition for the unit manager (which is issuing the callback)?

**Comment by vivek-bala** [comment] 2015-01-05 17:44
This is reproducible. It failed after 6 iterations for me.
```
Cycle : 7
Preprocessing stage ....
[Callback]: ComputeUnit '54aac60054737d392a0630b8' state changed to PendingExecution.
[Callback]: ComputeUnit '54aac60054737d392a0630b8' state changed to Scheduling.
[Callback]: ComputeUnit '54aac60054737d392a0630b8' state changed to Executing.
[Callback]: ComputeUnit '54aac60054737d392a0630b8' state changed to Done.
Starting Analysis
Submitting COCO Compute Unit
[Callback]: ComputeUnit '54aac60354737d392a0630b9' state changed to PendingExecution.
[Callback]: ComputeUnit '54aac60354737d392a0630b9' state changed to Executing.
[Callback]: ComputeUnit '54aac60354737d392a0630b9' state changed to StagingOutput.
[Callback]: ComputeUnit '54aac60354737d392a0630b9' state changed to Done.
Analysis Execution time :  45.066
Starting Simulation
[Callback]: ComputeUnit '54aac64554737d392a0630c0' state changed to PendingExecution.
[Callback]: ComputeUnit '54aac64554737d392a0630bb' state changed to PendingExecution.
[Callback]: ComputeUnit '54aac64554737d392a0630bf' state changed to PendingExecution.
[Callback]: ComputeUnit '54aac64554737d392a0630c8' state changed to PendingExecution.
[Callback]: ComputeUnit '54aac64554737d392a0630c9' state changed to PendingExecution.
[Callback]: ComputeUnit '54aac64554737d392a0630c0' state changed to Scheduling.
[Callback]: ComputeUnit '54aac64554737d392a0630c4' state changed to PendingExecution.
[Callback]: ComputeUnit '54aac64554737d392a0630c5' state changed to PendingExecution.
[Callback]: ComputeUnit '54aac64554737d392a0630c6' state changed to PendingExecution.
[Callback]: ComputeUnit '54aac64554737d392a0630c7' state changed to PendingExecution.
[Callback]: ComputeUnit '54aac64554737d392a0630bc' state changed to Scheduling.
[Callback]: ComputeUnit '54aac64554737d392a0630c0' state changed to Executing.
[Callback]: ComputeUnit '54aac64554737d392a0630ba' state changed to Scheduling.
[Callback]: ComputeUnit '54aac64554737d392a0630bb' state changed to Executing.
[Callback]: ComputeUnit '54aac64554737d392a0630bd' state changed to PendingExecution.
[Callback]: ComputeUnit '54aac64554737d392a0630c2' state changed to PendingExecution.
[Callback]: ComputeUnit '54aac64554737d392a0630c3' state changed to PendingExecution.
[Callback]: ComputeUnit '54aac64554737d392a0630bc' state changed to Executing.
[Callback]: ComputeUnit '54aac64554737d392a0630ba' state changed to Executing.
[Callback]: ComputeUnit '54aac64554737d392a0630bd' state changed to Executing.
[Callback]: ComputeUnit '54aac64554737d392a0630be' state changed to Executing.
[Callback]: ComputeUnit '54aac64554737d392a0630bf' state changed to Executing.
[Callback]: ComputeUnit '54aac64554737d392a0630c1' state changed to Scheduling.
[Callback]: ComputeUnit '54aac64554737d392a0630c2' state changed to Scheduling.
[Callback]: ComputeUnit '54aac64554737d392a0630c1' state changed to Executing.
[Callback]: ComputeUnit '54aac64554737d392a0630c3' state changed to Scheduling.
[Callback]: ComputeUnit '54aac64554737d392a0630c4' state changed to Scheduling.
[Callback]: ComputeUnit '54aac64554737d392a0630c5' state changed to Scheduling.
[Callback]: ComputeUnit '54aac64554737d392a0630c6' state changed to Scheduling.
[Callback]: ComputeUnit '54aac64554737d392a0630c7' state changed to Scheduling.
[Callback]: ComputeUnit '54aac64554737d392a0630c8' state changed to Scheduling.
[Callback]: ComputeUnit '54aac64554737d392a0630c0' state changed to Done.
[Callback]: ComputeUnit '54aac64554737d392a0630c4' state changed to Executing.
[Callback]: ComputeUnit '54aac64554737d392a0630c5' state changed to Executing.
[Callback]: ComputeUnit '54aac64554737d392a0630c6' state changed to Executing.
[Callback]: ComputeUnit '54aac64554737d392a0630c9' state changed to Scheduling.
[Callback]: ComputeUnit '54aac64554737d392a0630bb' state changed to Done.
[Callback]: ComputeUnit '54aac64554737d392a0630ba' state changed to Done.
[Callback]: ComputeUnit '54aac64554737d392a0630bc' state changed to Done.
[Callback]: ComputeUnit '54aac64554737d392a0630bd' state changed to Done.
[Callback]: ComputeUnit '54aac64554737d392a0630be' state changed to Done.
[Callback]: ComputeUnit '54aac64554737d392a0630bf' state changed to Done.
[Callback]: ComputeUnit '54aac64554737d392a0630c1' state changed to Done.
[Callback]: ComputeUnit '54aac64554737d392a0630c2' state changed to Executing.
[Callback]: ComputeUnit '54aac64554737d392a0630c3' state changed to Executing.
[Callback]: ComputeUnit '54aac64a54737d392a0630ca' state changed to PendingExecution.
[Callback]: ComputeUnit '54aac64554737d392a0630c7' state changed to Executing.
[Callback]: ComputeUnit '54aac64554737d392a0630c8' state changed to Executing.
[Callback]: ComputeUnit '54aac64554737d392a0630c9' state changed to Executing.
[Callback]: ComputeUnit '54aac64554737d392a0630c5' state changed to Done.
[Callback]: ComputeUnit '54aac64554737d392a0630c4' state changed to Done.
[Callback]: ComputeUnit '54aac64554737d392a0630c6' state changed to Done.
[Callback]: ComputeUnit '54aac64a54737d392a0630ca' state changed to Scheduling.
[Callback]: ComputeUnit '54aac64b54737d392a0630cb' state changed to PendingExecution.
[Callback]: ComputeUnit '54aac64a54737d392a0630ca' state changed to Executing.
[Callback]: ComputeUnit '54aac64554737d392a0630c3' state changed to Done.
[Callback]: ComputeUnit '54aac64554737d392a0630c7' state changed to Done.
[Callback]: ComputeUnit '54aac64554737d392a0630c2' state changed to Done.
[Callback]: ComputeUnit '54aac64554737d392a0630c8' state changed to Done.
[Callback]: ComputeUnit '54aac64554737d392a0630c9' state changed to Done.
[Callback]: ComputeUnit '54aac64b54737d392a0630cb' state changed to Executing.
[Callback]: ComputeUnit '54aac64b54737d392a0630cc' state changed to Executing.
[Callback]: ComputeUnit '54aac64c54737d392a0630cd' state changed to Scheduling.
[Callback]: ComputeUnit '54aac64d54737d392a0630ce' state changed to PendingExecution.
[Callback]: ComputeUnit '54aac64c54737d392a0630cd' state changed to Executing.
[Callback]: ComputeUnit '54aac64d54737d392a0630cf' state changed to PendingExecution.
[Callback]: ComputeUnit '54aac64d54737d392a0630ce' state changed to Scheduling.
[Callback]: ComputeUnit '54aac64e54737d392a0630d1' state changed to PendingExecution.
[Callback]: ComputeUnit '54aac64d54737d392a0630ce' state changed to Executing.
[Callback]: ComputeUnit '54aac64e54737d392a0630d0' state changed to Executing.
[Callback]: ComputeUnit '54aac64d54737d392a0630cf' state changed to Executing.
[Callback]: ComputeUnit '54aac64f54737d392a0630d2' state changed to PendingExecution.
[Callback]: ComputeUnit '54aac64f54737d392a0630d3' state changed to PendingExecution.
[Callback]: ComputeUnit '54aac64e54737d392a0630d1' state changed to Executing.
[Callback]: ComputeUnit '54aac64f54737d392a0630d3' state changed to Scheduling.
[Callback]: ComputeUnit '54aac64f54737d392a0630d2' state changed to Scheduling.
[Callback]: ComputeUnit '54aac65054737d392a0630d4' state changed to Scheduling.
[Callback]: ComputeUnit '54aac65054737d392a0630d5' state changed to PendingExecution.
[Callback]: ComputeUnit '54aac64d54737d392a0630cf' state changed to StagingOutput.
[Callback]: ComputeUnit '54aac65154737d392a0630d6' state changed to PendingExecution.
[Callback]: ComputeUnit '54aac65054737d392a0630d5' state changed to Scheduling.
[Callback]: ComputeUnit '54aac64f54737d392a0630d3' state changed to Executing.
[Callback]: ComputeUnit '54aac65154737d392a0630d6' state changed to Scheduling.
[Callback]: ComputeUnit '54aac65154737d392a0630d7' state changed to Scheduling.
[Callback]: ComputeUnit '54aac65254737d392a0630d8' state changed to PendingExecution.
[Callback]: ComputeUnit '54aac65254737d392a0630d9' state changed to PendingExecution.
[Callback]: ComputeUnit '54aac65254737d392a0630d8' state changed to Scheduling.
[Callback]: ComputeUnit '54aac65254737d392a0630d9' state changed to Scheduling.
[Callback]: ComputeUnit '54aac64d54737d392a0630cf' state changed to Done.
[Callback]: ComputeUnit '54aac64a54737d392a0630ca' state changed to StagingOutput.
[Callback]: ComputeUnit '54aac65154737d392a0630d6' state changed to Executing.
[Callback]: ComputeUnit '54aac64b54737d392a0630cb' state changed to StagingOutput.
[Callback]: ComputeUnit '54aac64b54737d392a0630cc' state changed to StagingOutput.
[Callback]: ComputeUnit '54aac64c54737d392a0630cd' state changed to StagingOutput.
[Callback]: ComputeUnit '54aac65054737d392a0630d5' state changed to Executing.
[Callback]: ComputeUnit '54aac64d54737d392a0630ce' state changed to StagingOutput.
[Callback]: ComputeUnit '54aac65154737d392a0630d7' state changed to Executing.
[Callback]: ComputeUnit '54aac65254737d392a0630d8' state changed to Executing.
[Callback]: ComputeUnit '54aac65254737d392a0630d9' state changed to Executing.
[Callback]: ComputeUnit '54aac64e54737d392a0630d0' state changed to StagingOutput.
[Callback]: ComputeUnit '54aac65054737d392a0630d4' state changed to Executing.
[Callback]: ComputeUnit '54aac65154737d392a0630d7' state changed to Failed.
#######################
##       ERROR       ##
#######################
ComputeUnit 54aac65154737d392a0630d7 has FAILED. Can't recover.
ComputeUnit log: [<radical.pilot.logentry.Logentry object at 0x7fc4985a64d0>]
STDERR : ln: creating hard link `./STDERR': File exists
ln: creating hard link `./STDOUT': File exists
[cli_0]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[c409-004.stampede.tacc.utexas.edu:mpispawn_0][readline] Unexpected End-Of-File on file descriptor 5. MPI process died?
[c409-004.stampede.tacc.utexas.edu:mpispawn_0][mtpmi_processops] Error while reading PMI socket. MPI process died?
[c409-004.stampede.tacc.utexas.edu:mpispawn_0][child_handler] MPI process (rank: 0, pid: 56564) exited with status 1
ln: accessing `md7.ncdf': No such file or directory

STDOUT : TACC: Starting up job 4662412
TACC: Setting up parallel environment for MVAPICH2+mpispawn.
TACC: Starting parallel tasks...
TACC: MPI job exited with code: 1
 
TACC: Shutdown complete. Exiting.

Execution was interrupted
Closing session, exiting now ...
[Callback]: ComputePilot '54aac34b54737d392a062fc9' state changed to Canceled.
```

**Comment by vivek-bala** [comment] 2015-01-06 11:03
The above trial was from the Nottingham machine. I'm not able to reproduce this from my machine or a VM.

**Comment by oleweidner** [comment] 2015-01-06 11:17
Hmmm.... odd. Can you attach the full log of the failing run on the Nottingham workstation?

**Comment by vivek-bala** [comment] 2015-01-06 12:21
Callbacks log : https://gist.github.com/vivek-bala/3ba193efd07ea1ccc3e9
Verbose log : https://gist.githubusercontent.com/vivek-bala/1781dd4e31feebfd1434/raw/extasy_notts_verbose_log

**Comment by oleweidner** [comment] 2015-01-06 13:17
Hm, so there is clearly something not working with your file management / linking strategy. The compute unit fails with an MPI error because the input file cannot be found. 

Does all linking / copying happen only on the remote, i.e., execution host or do you do anything localloy as well? I'm trying to understand why this only pops up on the Nottingham machines. 

Next, can you check if the file the MPI process cannot find, md4.ncdf (https://gist.github.com/vivek-bala/3ba193efd07ea1ccc3e9#file-extasy_notts_op_log-L695) is actually there or not? 

If it is there, could it be that we are seeing an issue similar to "the Lustre issue" that hit us before, i.e., that the file is not transferred completely yet when the MPI process starts executing?

**Comment by ashkurti** [comment] 2015-02-10 15:17
The reported problem has to do with the fact that we do expect in the backup folder information on iterations 2, 4, 6, 8 whereas only information on iterations 2 and 4 is provided. I have repeated this test twice yesterday. I have the feeling that Vivek has been having the same problem after 6 iterations. 

ExTASY log at: https://gist.github.com/ashkurti/c6941a5ce75f91725a87

**Comment by vivek-bala** [comment] 2015-02-11 17:03
I think you are running out of walltime (60 mins) by the time execution reaches iteration-4-analysis. The pilot fails while the CU is executing, the CU does not fail. Could you try again with greater walltime please ?

**Comment by vivek-bala** [comment] 2015-02-11 17:04
```
2015:02:09 13:34:04 radical.pilot.MainProcess: [INFO    ] ComputePilot '54d8b6d9f8cdba480cde2f16' state changed from 'PendingActive' to 'Active'.
..
..
2015:02:09 14:34:13 radical.pilot.MainProcess: [ERROR   ] SAGA job state for ComputePilot 54d8b6d9f8cdba480cde2f16 is Canceled.
```

**Comment by ashkurti** [comment] 2015-02-16 12:18
I have tested this scenario again after increasing the pilot walltime to 90 mins. I still encounter problems but in order to concentrate better on this problem I have raised another issue #146

**Comment by vivek-bala** [comment] 2015-02-19 06:46
following 146

**Closed by vivek-bala** 2015-02-19 06:46 UTC
