### ISSUE TITLE
Understanding Simulation Execution Times for Gromacs/(lsdmap)

### ISSUE THREAD

**Issue by ebreitmo** [radical-cybertools/ExTASY#139] opened 2015-01-16 11:22 UTC
Hello,

When running lsdmap/gromacs from my mac onto ARCHER, using the latest radical-pilot and input files, I see Simulation Execution Times which are often about four times the value given in the example output.

 I ran with num_CUs=24, so for each cycle I get 24 unit-blabla directories, in each of which ‘aprun -n 1 python run.py —map grompp.mdp …’ is executed.
In each of these directories is a md.log file, where the wall time ‘X’ is given. Then there is wall time given four times in the STDERR file, the last entry corresponds to ‘X’. Often the first out of the four entries is about 3-4 times the following three values. The wall time ‘X’ is between 0.21-0.33s. The ‘Simulation Execution Time: 1995’ - in my latest run is  (!).
So even for a conservative estimate I only get

   24*0.3*3 + 24*0.3*4 = 50s

Even if I had the low numbers (~200s) expected for this run, where does all the time come from? The routine where ‘Simulation Execution Time’ gets calculated is 
extasy/bin/Simulator/Gromacs/simulator.py
   ….. 
    units = umgr.submit_units(gromacs_tasks)

    start_times = []
    end_times = []

    # Wait for all compute units to finish.                                                          
    umgr.wait_units()

    try:
        for unit in units:
            start_times.append(unit.start_time)
            end_times.append(unit.stop_time)

        print 'Simulation Execution Time : ', (max(end_times)-min(start_times)).total_seconds()

called by ../../runme.py, where
   session = radical.pilot.Session(database_url=RPconfig.DBURL)
   umgr = radical.pilot.UnitManager(session=session, scheduler=radical.pilot.SCHED_DIRECT_SUBMISSION)

Thanks, Elena

**Comment by vivek-bala** [comment] 2015-01-21 20:58
I haven't been able to get thru any of the queues to check this with the new files. Could it be a duplicate of #133 ? Could you verify the files you used were from config_files/ and input_files ? (these are the files pointed to by the links in the documentation)

**Comment by ebreitmo** [comment] 2015-01-22 09:13
Hi Vivek,

I use the docu at  

https://github.com/radical-cybertools/ExTASY/blob/devel/README.md




more gromacslsdmap.wcfg
#-------------------------Applications----------------------
simulator             = 'Gromacs'           # Simulator to be loaded
analyzer              = 'LSDMap'            # Analyzer to be loaded

#--------------------------General--------------------------------
num_CUs              = 2                   # Number of tasks or Compute Units
num_iterations       = 2                    # Number of iterations of Simulation-Analysis
start_iter           = 0                    # Iteration number with which to start
nsave                = 1                    # # Iterations after which output is transfered to local machine

#--------------------------Simulation--------------------------------
num_cores_per_sim_cu = 1                    # Number of cores per Simulation Compute Units
md_input_file        = './input.gro'        # Entire path to the MD Input file - Do not use $HOME or the likes
mdp_file             = './grompp.mdp'       # Entire path to the MD Parameters file - Do not use $HOME or the likes
top_file             = './topol.top'        # Entire path to the Topology file - Do not use $HOME or the likes
ndx_file             = None                   # Entire path to the Index file - Do not use $HOME or the likes
grompp_options       = None                   # Command line options for when grompp is used
mdrun_options        = None                   # Command line options for when mdrun is used
itp_file_loc         = None                   # Entire path to the location of .itp files - Do not use $HOME or the likes
md_output_file       = 'tmp.gro'            # Filename to be used for the simulation output

#--------------------------Analysis----------------------------------
lsdm_config_file     = './config.ini'       # Entire path to the LSDMap configuration file - Do not use $HOME or the likes
num_runs             = 100                # Number of runs to be performed in the Selection step in Analysis
w_file               = 'weight.w'           # Filename to be used for the weight file
max_alive_neighbors  = '10'                 # Maximum alive neighbors to be considered while reweighting
max_dead_neighbors   = '1'                  # Maximum dead neighbors to be considered while reweighing



more archer.rcfg
REMOTE_HOST = 'archer.ac.uk'              # Label/Name of the Remote Machine
UNAME       = 'ebreitmo'                  # Username on the Remote Machine
ALLOCATION  = 'e290'                      # Allocation to be charged
WALLTIME    = 20                          # Walltime to be requested for the pilot
PILOTSIZE   = 2                          # Number of cores to be reserved
WORKDIR     = '/work/e290/e290/ebreitmo'  # Working directory on the remote machine
QUEUE       = 'standard'                  # Name of the queue in the remote machine


DBURL = 'mongodb://ec2-54-221-194-147.compute-1.amazonaws.com:24242/'



Cheers,
Elena

---------------------------------------------------
Dr Elena Breitmoser

EPCC, University of Edinburgh
JCMB, Room 3401
Peter Guthrie Tait Road
UK-Edinburgh EH9 3FD

Tel: +44 131 650 6494




On 21 Jan 2015, at 20:58, Vivekanandan (Vivek) Balasubramanian <notifications@github.com> wrote:

> I haven't been able to get thru any of the queues to check this with the new files. Could it be a duplicate of #133 ? Could you verify the files you used were from config_files/ and input_files ? (these are the files pointed to by the links in the documentation)
> 
> —
> Reply to this email directly or view it on GitHub.
> 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by vivek-bala** [comment] 2015-01-22 10:37
This looks good. Could you verify if the gro file (input.gro) used had 2500 lines ?

**Comment by ebreitmo** [comment] 2015-01-22 10:39
wc -l input.gro 
    2500 input.gro



Cheers,
Elena

---------------------------------------------------
Dr Elena Breitmoser

EPCC, University of Edinburgh
JCMB, Room 3401
Peter Guthrie Tait Road
UK-Edinburgh EH9 3FD

Tel: +44 131 650 6494




On 22 Jan 2015, at 10:37, Vivekanandan (Vivek) Balasubramanian <notifications@github.com> wrote:

> This looks good. Could you verify if the gro file (input.gro) used had 2500 lines ?
> 
> —
> Reply to this email directly or view it on GitHub.
> 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by vivek-bala** [comment] 2015-01-22 10:59
I just noticed that the pilot size and the number of CUs is set 2, which would mean that each CU executes over 50 configurations (2500 lines = 100 configurations) in which case this timing is expected on Archer (similar case as #133 ). Could you try with pilot size=24 and num_CUs=24 ?

**Comment by ebreitmo** [comment] 2015-01-22 11:13
Sorry about the confusion. The numbers re time I reported in #issue139 are actually done with

	PILOTSIZE = 24
	num_CUs = 24



I attach the output generated on my MAC from the actual run, you’ll see from there that I used ’24’.


Cheers,
Elena

---------------------------------------------------
Dr Elena Breitmoser

EPCC, University of Edinburgh
JCMB, Room 3401
Peter Guthrie Tait Road
UK-Edinburgh EH9 3FD

Tel: +44 131 650 6494




On 22 Jan 2015, at 10:59, Vivekanandan (Vivek) Balasubramanian <notifications@github.com> wrote:

> I just noticed that the pilot size and the number of CUs is set 2, which would mean that each CU executes over 50 configurations (2500 lines = 100 configurations) in which case this timing is expected on Archer (similar case as #133 ). Could you try with pilot size=24 and num_CUs=24 ?
> 
> —
> Reply to this email directly or view it on GitHub.
> 
15Jan2015
MAC->ARCHER

Session UID: 54b7a14b4c917a025991a7ba 
Pilot UID       : 54b7a14c4c917a025991a7bc 
Loading kernel configurations from /Users/elenabreitmoser/13Jan2015/lib/python2.7/site-packages/radical/ensemblemd/mdkernels/configs/amber.json
Loading kernel configurations from /Users/elenabreitmoser/13Jan2015/lib/python2.7/site-packages/radical/ensemblemd/mdkernels/configs/coco.json
Loading kernel configurations from /Users/elenabreitmoser/13Jan2015/lib/python2.7/site-packages/radical/ensemblemd/mdkernels/configs/gromacs.json
Loading kernel configurations from /Users/elenabreitmoser/13Jan2015/lib/python2.7/site-packages/radical/ensemblemd/mdkernels/configs/lsdmap.json
Loading kernel configurations from /Users/elenabreitmoser/13Jan2015/lib/python2.7/site-packages/radical/ensemblemd/mdkernels/configs/mmpbsa.json
Loading kernel configurations from /Users/elenabreitmoser/13Jan2015/lib/python2.7/site-packages/radical/ensemblemd/mdkernels/configs/namd.json
Loading kernel configurations from /Users/elenabreitmoser/13Jan2015/lib/python2.7/site-packages/radical/ensemblemd/mdkernels/configs/sleep.json
Loading kernel configurations from /Users/elenabreitmoser/13Jan2015/lib/python2.7/site-packages/radical/ensemblemd/mdkernels/configs/test.json
Cycle : 0
Preprocessing stage ....
[Callback]: ComputeUnit '54b7a1504c917a025991a7be' state changed to PendingInputStaging.
[Callback]: ComputePilot '54b7a14c4c917a025991a7bc' state changed to Launching.
[Callback]: ComputeUnit '54b7a1504c917a025991a7be' state changed to StagingInput.
[Callback]: ComputeUnit '54b7a1504c917a025991a7be' state changed to PendingExecution.
[Callback]: ComputePilot '54b7a14c4c917a025991a7bc' state changed to PendingActive.
[Callback]: ComputePilot '54b7a14c4c917a025991a7bc' state changed to Active.
[Callback]: ComputeUnit '54b7a1504c917a025991a7be' state changed to Scheduling.
[Callback]: ComputeUnit '54b7a1504c917a025991a7be' state changed to Executing.
[Callback]: ComputeUnit '54b7a1504c917a025991a7be' state changed to Done.
Starting Simulation
[Callback]: ComputeUnit '54b847e24c917a025991a7ce' state changed to PendingExecution.
[Callback]: ComputeUnit '54b847e24c917a025991a7c4' state changed to PendingExecution.
[Callback]: ComputeUnit '54b847e24c917a025991a7ca' state changed to PendingExecution.
[Callback]: ComputeUnit '54b847e24c917a025991a7c5' state changed to PendingExecution.
[Callback]: ComputeUnit '54b847e24c917a025991a7cf' state changed to PendingExecution.
[Callback]: ComputeUnit '54b847e24c917a025991a7c4' state changed to Scheduling.
[Callback]: ComputeUnit '54b847e24c917a025991a7c6' state changed to PendingExecution.
[Callback]: ComputeUnit '54b847e24c917a025991a7d0' state changed to PendingExecution.
[Callback]: ComputeUnit '54b847e24c917a025991a7c4' state changed to Executing.
[Callback]: ComputeUnit '54b847e24c917a025991a7c5' state changed to Scheduling.
[Callback]: ComputeUnit '54b847e24c917a025991a7c7' state changed to PendingExecution.
[Callback]: ComputeUnit '54b847e24c917a025991a7d1' state changed to PendingExecution.
[Callback]: ComputeUnit '54b847e24c917a025991a7bf' state changed to PendingExecution.
[Callback]: ComputeUnit '54b847e24c917a025991a7d5' state changed to PendingExecution.
[Callback]: ComputeUnit '54b847e24c917a025991a7c5' state changed to Executing.
[Callback]: ComputeUnit '54b847e24c917a025991a7c6' state changed to Scheduling.
[Callback]: ComputeUnit '54b847e24c917a025991a7c8' state changed to PendingExecution.
[Callback]: ComputeUnit '54b847e24c917a025991a7d4' state changed to PendingExecution.
[Callback]: ComputeUnit '54b847e24c917a025991a7c6' state changed to Executing.
[Callback]: ComputeUnit '54b847e24c917a025991a7bf' state changed to Scheduling.
[Callback]: ComputeUnit '54b847e24c917a025991a7c9' state changed to PendingExecution.
[Callback]: ComputeUnit '54b847e24c917a025991a7d6' state changed to PendingExecution.
[Callback]: ComputeUnit '54b847e24c917a025991a7c0' state changed to PendingExecution.
[Callback]: ComputeUnit '54b847e24c917a025991a7cb' state changed to PendingExecution.
[Callback]: ComputeUnit '54b847e24c917a025991a7bf' state changed to Executing.
[Callback]: ComputeUnit '54b847e24c917a025991a7c7' state changed to Scheduling.
[Callback]: ComputeUnit '54b847e24c917a025991a7c1' state changed to PendingExecution.
[Callback]: ComputeUnit '54b847e24c917a025991a7c3' state changed to PendingExecution.
[Callback]: ComputeUnit '54b847e24c917a025991a7c7' state changed to Executing.
[Callback]: ComputeUnit '54b847e24c917a025991a7c0' state changed to Scheduling.
[Callback]: ComputeUnit '54b847e24c917a025991a7d2' state changed to PendingExecution.
[Callback]: ComputeUnit '54b847e24c917a025991a7d3' state changed to PendingExecution.
[Callback]: ComputeUnit '54b847e24c917a025991a7c2' state changed to PendingExecution.
[Callback]: ComputeUnit '54b847e24c917a025991a7cc' state changed to PendingExecution.
[Callback]: ComputeUnit '54b847e24c917a025991a7c0' state changed to Executing.
[Callback]: ComputeUnit '54b847e24c917a025991a7c1' state changed to Scheduling.
[Callback]: ComputeUnit '54b847e24c917a025991a7cd' state changed to PendingExecution.
[Callback]: ComputeUnit '54b847e24c917a025991a7c1' state changed to Executing.
[Callback]: ComputeUnit '54b847e24c917a025991a7c2' state changed to Scheduling.
[Callback]: ComputeUnit '54b847e24c917a025991a7c2' state changed to Executing.
[Callback]: ComputeUnit '54b847e24c917a025991a7c3' state changed to Scheduling.
[Callback]: ComputeUnit '54b847e24c917a025991a7c3' state changed to Executing.
[Callback]: ComputeUnit '54b847e24c917a025991a7c8' state changed to Scheduling.
[Callback]: ComputeUnit '54b847e24c917a025991a7c9' state changed to Scheduling.
[Callback]: ComputeUnit '54b847e24c917a025991a7c8' state changed to Executing.
[Callback]: ComputeUnit '54b847e24c917a025991a7c9' state changed to Executing.
[Callback]: ComputeUnit '54b847e24c917a025991a7ca' state changed to Scheduling.
[Callback]: ComputeUnit '54b847e24c917a025991a7ca' state changed to Executing.
[Callback]: ComputeUnit '54b847e24c917a025991a7cb' state changed to Scheduling.
[Callback]: ComputeUnit '54b847e24c917a025991a7cb' state changed to Executing.
[Callback]: ComputeUnit '54b847e24c917a025991a7cc' state changed to Scheduling.
[Callback]: ComputeUnit '54b847e24c917a025991a7cd' state changed to Scheduling.
[Callback]: ComputeUnit '54b847e24c917a025991a7cc' state changed to Executing.
[Callback]: ComputeUnit '54b847e24c917a025991a7cd' state changed to Executing.
[Callback]: ComputeUnit '54b847e24c917a025991a7ce' state changed to Scheduling.
[Callback]: ComputeUnit '54b847e24c917a025991a7cf' state changed to Scheduling.
[Callback]: ComputeUnit '54b847e24c917a025991a7ce' state changed to Executing.
[Callback]: ComputeUnit '54b847e24c917a025991a7cf' state changed to Executing.
[Callback]: ComputeUnit '54b847e24c917a025991a7d0' state changed to Scheduling.
[Callback]: ComputeUnit '54b847e24c917a025991a7d1' state changed to Scheduling.
[Callback]: ComputeUnit '54b847e24c917a025991a7d0' state changed to Executing.
[Callback]: ComputeUnit '54b847e24c917a025991a7d2' state changed to Scheduling.
[Callback]: ComputeUnit '54b847e24c917a025991a7d1' state changed to Executing.
[Callback]: ComputeUnit '54b847e24c917a025991a7d2' state changed to Executing.
[Callback]: ComputeUnit '54b847e24c917a025991a7d3' state changed to Scheduling.
[Callback]: ComputeUnit '54b847e24c917a025991a7d3' state changed to Executing.
[Callback]: ComputeUnit '54b847e24c917a025991a7d4' state changed to Scheduling.
[Callback]: ComputeUnit '54b847e24c917a025991a7d4' state changed to Executing.
[Callback]: ComputeUnit '54b847e24c917a025991a7d5' state changed to Scheduling.
[Callback]: ComputeUnit '54b847e24c917a025991a7d5' state changed to Executing.
[Callback]: ComputeUnit '54b847e24c917a025991a7d6' state changed to Scheduling.
[Callback]: ComputeUnit '54b847e24c917a025991a7d6' state changed to Executing.
[Callback]: ComputeUnit '54b847e24c917a025991a7c4' state changed to Done.
[Callback]: ComputeUnit '54b847e24c917a025991a7ca' state changed to Done.
[Callback]: ComputeUnit '54b847e24c917a025991a7bf' state changed to Done.
[Callback]: ComputeUnit '54b847e24c917a025991a7c7' state changed to Done.
[Callback]: ComputeUnit '54b847e24c917a025991a7c5' state changed to Done.
[Callback]: ComputeUnit '54b847e24c917a025991a7d6' state changed to Done.
[Callback]: ComputeUnit '54b847e24c917a025991a7ce' state changed to Done.
[Callback]: ComputeUnit '54b847e24c917a025991a7cb' state changed to Done.
[Callback]: ComputeUnit '54b847e24c917a025991a7c8' state changed to Done.
[Callback]: ComputeUnit '54b847e24c917a025991a7c6' state changed to Done.
[Callback]: ComputeUnit '54b847e24c917a025991a7cc' state changed to Done.
[Callback]: ComputeUnit '54b847e24c917a025991a7c9' state changed to Done.
[Callback]: ComputeUnit '54b847e24c917a025991a7c2' state changed to Done.
[Callback]: ComputeUnit '54b847e24c917a025991a7d4' state changed to Done.
[Callback]: ComputeUnit '54b847e24c917a025991a7d5' state changed to Done.
[Callback]: ComputeUnit '54b847e24c917a025991a7cd' state changed to Done.
[Callback]: ComputeUnit '54b847e24c917a025991a7c3' state changed to Done.
[Callback]: ComputeUnit '54b847e24c917a025991a7c0' state changed to Done.
[Callback]: ComputeUnit '54b847e24c917a025991a7d3' state changed to Done.
[Callback]: ComputeUnit '54b847e24c917a025991a7d0' state changed to Done.
[Callback]: ComputeUnit '54b847e24c917a025991a7cf' state changed to Done.
[Callback]: ComputeUnit '54b847e24c917a025991a7d1' state changed to Done.
[Callback]: ComputeUnit '54b847e24c917a025991a7d2' state changed to Done.
[Callback]: ComputeUnit '54b847e24c917a025991a7c1' state changed to Done.
Simulation Execution Time :  1995.735
Starting Analysis
[Callback]: ComputeUnit '54b84fb04c917a025991a7d7' state changed to PendingExecution.
[Callback]: ComputeUnit '54b84fb04c917a025991a7d7' state changed to Scheduling.
[Callback]: ComputeUnit '54b84fb04c917a025991a7d7' state changed to Executing.
[Callback]: ComputeUnit '54b84fb04c917a025991a7d7' state changed to Done.
Select + Reweighting step
[Callback]: ComputeUnit '54b850324c917a025991a7d8' state changed to PendingExecution.
[Callback]: ComputeUnit '54b850324c917a025991a7d8' state changed to Scheduling.
[Callback]: ComputeUnit '54b850324c917a025991a7d8' state changed to Executing.
[Callback]: ComputeUnit '54b850324c917a025991a7d8' state changed to StagingOutput.
[Callback]: ComputeUnit '54b850324c917a025991a7d8' state changed to Done.
Analysis Execution time :  137.501
Creating backup...
Cycle : 1
Preprocessing stage ....
[Callback]: ComputeUnit '54b850444c917a025991a7d9' state changed to PendingInputStaging.
[Callback]: ComputeUnit '54b850444c917a025991a7d9' state changed to StagingInput.
[Callback]: ComputeUnit '54b850444c917a025991a7d9' state changed to PendingExecution.
[Callback]: ComputeUnit '54b850444c917a025991a7d9' state changed to Scheduling.
[Callback]: ComputeUnit '54b850444c917a025991a7d9' state changed to Executing.
[Callback]: ComputeUnit '54b850444c917a025991a7d9' state changed to Done.
Starting Simulation
[Callback]: ComputeUnit '54b850714c917a025991a7e6' state changed to PendingExecution.
[Callback]: ComputeUnit '54b850724c917a025991a7ea' state changed to PendingExecution.
[Callback]: ComputeUnit '54b850724c917a025991a7f1' state changed to PendingExecution.
[Callback]: ComputeUnit '54b850714c917a025991a7de' state changed to PendingExecution.
[Callback]: ComputeUnit '54b850714c917a025991a7df' state changed to PendingExecution.
[Callback]: ComputeUnit '54b850714c917a025991a7e1' state changed to PendingExecution.
[Callback]: ComputeUnit '54b850714c917a025991a7e3' state changed to PendingExecution.
[Callback]: ComputeUnit '54b850724c917a025991a7e9' state changed to PendingExecution.
[Callback]: ComputeUnit '54b850724c917a025991a7ec' state changed to PendingExecution.
[Callback]: ComputeUnit '54b850714c917a025991a7e0' state changed to PendingExecution.
[Callback]: ComputeUnit '54b850714c917a025991a7e2' state changed to PendingExecution.
[Callback]: ComputeUnit '54b850724c917a025991a7f0' state changed to PendingExecution.
[Callback]: ComputeUnit '54b850714c917a025991a7de' state changed to Executing.
[Callback]: ComputeUnit '54b850714c917a025991a7da' state changed to Scheduling.
[Callback]: ComputeUnit '54b850724c917a025991a7ee' state changed to PendingExecution.
[Callback]: ComputeUnit '54b850714c917a025991a7db' state changed to PendingExecution.
[Callback]: ComputeUnit '54b850714c917a025991a7e7' state changed to PendingExecution.
[Callback]: ComputeUnit '54b850724c917a025991a7ed' state changed to PendingExecution.
[Callback]: ComputeUnit '54b850714c917a025991a7da' state changed to Executing.
[Callback]: ComputeUnit '54b850724c917a025991a7ec' state changed to Executing.
[Callback]: ComputeUnit '54b850724c917a025991a7eb' state changed to Scheduling.
[Callback]: ComputeUnit '54b850714c917a025991a7dc' state changed to PendingExecution.
[Callback]: ComputeUnit '54b850714c917a025991a7dd' state changed to PendingExecution.
[Callback]: ComputeUnit '54b850714c917a025991a7e4' state changed to PendingExecution.
[Callback]: ComputeUnit '54b850714c917a025991a7e5' state changed to PendingExecution.
[Callback]: ComputeUnit '54b850724c917a025991a7ef' state changed to PendingExecution.
[Callback]: ComputeUnit '54b850724c917a025991a7eb' state changed to Executing.
[Callback]: ComputeUnit '54b850724c917a025991a7ee' state changed to Scheduling.
[Callback]: ComputeUnit '54b850714c917a025991a7e8' state changed to PendingExecution.
[Callback]: ComputeUnit '54b850714c917a025991a7db' state changed to Executing.
[Callback]: ComputeUnit '54b850714c917a025991a7dc' state changed to Scheduling.
[Callback]: ComputeUnit '54b850724c917a025991a7ee' state changed to Executing.
[Callback]: ComputeUnit '54b850714c917a025991a7dc' state changed to Executing.
[Callback]: ComputeUnit '54b850714c917a025991a7dd' state changed to Executing.
[Callback]: ComputeUnit '54b850714c917a025991a7df' state changed to Scheduling.
[Callback]: ComputeUnit '54b850714c917a025991a7df' state changed to Executing.
[Callback]: ComputeUnit '54b850714c917a025991a7e0' state changed to Scheduling.
[Callback]: ComputeUnit '54b850714c917a025991a7e1' state changed to Executing.
[Callback]: ComputeUnit '54b850714c917a025991a7e2' state changed to Scheduling.
[Callback]: ComputeUnit '54b850714c917a025991a7e0' state changed to Executing.
[Callback]: ComputeUnit '54b850714c917a025991a7e2' state changed to Executing.
[Callback]: ComputeUnit '54b850714c917a025991a7e4' state changed to Scheduling.
[Callback]: ComputeUnit '54b850714c917a025991a7e3' state changed to Executing.
[Callback]: ComputeUnit '54b850714c917a025991a7e4' state changed to Executing.
[Callback]: ComputeUnit '54b850714c917a025991a7e5' state changed to Scheduling.
[Callback]: ComputeUnit '54b850714c917a025991a7e5' state changed to Executing.
[Callback]: ComputeUnit '54b850714c917a025991a7e6' state changed to Executing.
[Callback]: ComputeUnit '54b850714c917a025991a7e7' state changed to Scheduling.
[Callback]: ComputeUnit '54b850724c917a025991a7e9' state changed to Scheduling.
[Callback]: ComputeUnit '54b850714c917a025991a7e7' state changed to Executing.
[Callback]: ComputeUnit '54b850714c917a025991a7e8' state changed to Scheduling.
[Callback]: ComputeUnit '54b850724c917a025991a7e9' state changed to Executing.
[Callback]: ComputeUnit '54b850724c917a025991a7ea' state changed to Scheduling.
[Callback]: ComputeUnit '54b850714c917a025991a7e8' state changed to Executing.
[Callback]: ComputeUnit '54b850724c917a025991a7ea' state changed to Executing.
[Callback]: ComputeUnit '54b850724c917a025991a7ed' state changed to Scheduling.
[Callback]: ComputeUnit '54b850724c917a025991a7ef' state changed to Scheduling.
[Callback]: ComputeUnit '54b850724c917a025991a7ed' state changed to Executing.
[Callback]: ComputeUnit '54b850724c917a025991a7ef' state changed to Executing.
[Callback]: ComputeUnit '54b850724c917a025991a7f0' state changed to Scheduling.
[Callback]: ComputeUnit '54b850724c917a025991a7f0' state changed to Executing.
[Callback]: ComputeUnit '54b850724c917a025991a7f1' state changed to Scheduling.
[Callback]: ComputeUnit '54b850724c917a025991a7f1' state changed to Executing.
[Callback]: ComputeUnit '54b850714c917a025991a7de' state changed to Done.
[Callback]: ComputeUnit '54b850714c917a025991a7e5' state changed to Done.
[Callback]: ComputeUnit '54b850724c917a025991a7eb' state changed to Done.
[Callback]: ComputeUnit '54b850724c917a025991a7ea' state changed to Done.
[Callback]: ComputeUnit '54b850714c917a025991a7dc' state changed to Done.
[Callback]: ComputeUnit '54b850724c917a025991a7f1' state changed to Done.
[Callback]: ComputeUnit '54b850714c917a025991a7e6' state changed to Done.
[Callback]: ComputeUnit '54b850714c917a025991a7e2' state changed to Done.
[Callback]: ComputeUnit '54b850714c917a025991a7e0' state changed to Done.
[Callback]: ComputeUnit '54b850714c917a025991a7dd' state changed to Done.
[Callback]: ComputeUnit '54b850714c917a025991a7e8' state changed to Done.
[Callback]: ComputeUnit '54b850714c917a025991a7df' state changed to Done.
[Callback]: ComputeUnit '54b850724c917a025991a7ec' state changed to Done.
[Callback]: ComputeUnit '54b850724c917a025991a7e9' state changed to Done.
[Callback]: ComputeUnit '54b850714c917a025991a7e1' state changed to Done.
[Callback]: ComputeUnit '54b850714c917a025991a7da' state changed to Done.
[Callback]: ComputeUnit '54b850714c917a025991a7e7' state changed to Done.
[Callback]: ComputeUnit '54b850724c917a025991a7f0' state changed to Done.
[Callback]: ComputeUnit '54b850724c917a025991a7ee' state changed to Done.
[Callback]: ComputeUnit '54b850714c917a025991a7e4' state changed to Done.
[Callback]: ComputeUnit '54b850714c917a025991a7e3' state changed to Done.
[Callback]: ComputeUnit '54b850724c917a025991a7ef' state changed to Done.
[Callback]: ComputeUnit '54b850724c917a025991a7ed' state changed to Done.
[Callback]: ComputeUnit '54b850714c917a025991a7db' state changed to Done.
Simulation Execution Time :  345.61
Starting Analysis
[Callback]: ComputeUnit '54b851ce4c917a025991a7f2' state changed to PendingExecution.
[Callback]: ComputeUnit '54b851ce4c917a025991a7f2' state changed to Executing.
[Callback]: ComputeUnit '54b851ce4c917a025991a7f2' state changed to Done.
Select + Reweighting step
[Callback]: ComputeUnit '54b851e24c917a025991a7f3' state changed to Executing.
[Callback]: ComputeUnit '54b851e24c917a025991a7f3' state changed to StagingOutput.
[Callback]: ComputeUnit '54b851e24c917a025991a7f3' state changed to Done.
Analysis Execution time :  22.285
Creating backup...
Closing session, exiting now ...
[Callback]: ComputePilot '54b7a14c4c917a025991a7bc' state changed to Canceled.


more archer.rcfg
REMOTE_HOST = 'archer.ac.uk'              # Label/Name of the Remote Machine
UNAME       = 'ebreitmo'                  # Username on the Remote Machine
ALLOCATION  = 'e290'                      # Allocation to be charged
WALLTIME    = 60                          # Walltime to be requested for the pilot
PILOTSIZE   = 24                          # Number of cores to be reserved
WORKDIR     = '/work/e290/e290/ebreitmo'  # Working directory on the remote machine
QUEUE       = 'standard'                  # Name of the queue in the remote machine


more gromacslsdmap.wcfg
#-------------------------Applications----------------------
simulator             = 'Gromacs'           # Simulator to be loaded
analyzer              = 'LSDMap'            # Analyzer to be loaded

#--------------------------General--------------------------------
num_CUs              = 24                   # Number of tasks or Compute Units
num_iterations       = 2                    # Number of iterations of Simulation-Analysis
start_iter           = 0                    # Iteration number with which to start
nsave                = 1                    # # Iterations after which output is transfered to local machine

#--------------------------Simulation--------------------------------
num_cores_per_sim_cu = 1                    # Number of cores per Simulation Compute Units
md_input_file        = './input.gro'        # Entire path to the MD Input file - Do not use $HOME or the likes
mdp_file             = './grompp.mdp'       # Entire path to the MD Parameters file - Do not use $HOME or the likes
top_file             = './topol.top'        # Entire path to the Topology file - Do not use $HOME or the likes
ndx_file             = None                   # Entire path to the Index file - Do not use $HOME or the likes
grompp_options       = None                   # Command line options for when grompp is used
mdrun_options        = None                   # Command line options for when mdrun is used
itp_file_loc         = None                   # Entire path to the location of .itp files - Do not use $HOME or the likes
md_output_file       = 'tmp.gro'            # Filename to be used for the simulation output

#--------------------------Analysis----------------------------------
lsdm_config_file     = './config.ini'       # Entire path to the LSDMap configuration file - Do not use $HOME or the likes
num_runs             = 100                # Number of runs to be performed in the Selection step in Analysis
w_file               = 'weight.w'           # Filename to be used for the weight file
max_alive_neighbors  = '10'                 # Maximum alive neighbors to be considered while reweighting
max_dead_neighbors   = '1'                  # Maximum dead neighbors to be considered while reweighting
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by vivek-bala** [comment] 2015-01-22 11:32
Hmmm, the second iteration timings are in the expected range while the first is not. Could you mail me all the data in one of the simulation CUs from the first iteration ? I can't understand why there is such a huge difference.

**Comment by ebreitmo** [comment] 2015-01-22 11:38
Cheers,
Elena

---------------------------------------------------
Dr Elena Breitmoser

EPCC, University of Edinburgh
JCMB, Room 3401
Peter Guthrie Tait Road
UK-Edinburgh EH9 3FD

Tel: +44 131 650 6494




On 22 Jan 2015, at 11:32, Vivekanandan (Vivek) Balasubramanian <notifications@github.com> wrote:

> Hmmm, the second iteration timings are in the expected range while the first is not. Could you mail me all the data in one of the simulation CUs from the first iteration ? I can't understand why there is such a huge difference.
> 
> —
> Reply to this email directly or view it on GitHub.
> 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by vivek-bala** [comment] 2015-01-22 19:26
So I observed that the gromacs simulation time is highly variable. In this script, https://gist.github.com/vivek-bala/82953862a45d889e8ce4, I have the logs from 2 grlsd-on-archer back-to-back executions.

Simulation time in the first iteration is 914.511 while in the second it is 210.11. No parameters were changed in the two executions.

I am not sure if this is the behaviour of radical pilot or gromacs on the system.

**Comment by oleweidner** [comment] 2015-01-25 16:50
Hi Vivek,

can you try to run the RADICAL-Pilot benchmarking tool http://radicalpilot.readthedocs.org/en/latest/benchmarks.html <http://radicalpilot.readthedocs.org/en/latest/benchmarks.html>? This should give us an idea how things are behaving on the radical-pilot end.

However, are you sure that GROMACS is supposed to have homogeneous execution times across iterations? Only if that is the case, we should start looking further into radical-pilot execution. Did you ever end up with varying execution times for the same iteration across different runs?

Cheers
Ole

**Comment by vivek-bala** [comment] 2015-01-26 19:08
I haven't been able to reproduce this case where the simulations takes ~1000 seconds. @ebreitmo , could you try this with EXTASY_DEBUG set to True. I'll keep trying as well.

@oleweidner , I think I have not explained properly, in https://gist.github.com/vivek-bala/82953862a45d889e8ce4, I have run the experiment twice. 2 iterations in each trial. In the first trial, the simulation in the 1st iteration takes ~900 seconds while in the second trial, the same simulation in the 1st iteration takes ~210 seconds. So in effect, the same simulation stage in iteration no. 1 takes different execution times in two different trials/attempts.

**Comment by ebreitmo** [comment] 2015-01-27 10:58
It’s very weird. now that we are looking for long run times, all times are below 300s…I have been trying several runs today.


Cheers,
Elena

---------------------------------------------------
Dr Elena Breitmoser

EPCC, University of Edinburgh
JCMB, Room 3401
Peter Guthrie Tait Road
UK-Edinburgh EH9 3FD

Tel: +44 131 650 6494




On 26 Jan 2015, at 19:08, Vivekanandan (Vivek) Balasubramanian <notifications@github.com> wrote:

> I haven't been able to reproduce this case where the simulations takes ~1000 seconds. @ebreitmo , could you try this with EXTASY_DEBUG set to True. I'll keep trying as well.
> 
> @oleweidner , I think I have not explained properly, in https://gist.github.com/vivek-bala/82953862a45d889e8ce4, I have run the experiment twice. 2 iterations in each trial. In the first trial, the simulation in the 1st iteration takes ~900 seconds while in the second trial, the same simulation in the 1st iteration takes ~210 seconds. So in effect, the same simulation stage in iteration no. 1 takes different execution times in two different trials/attempts.
> 
> —
> Reply to this email directly or view it on GitHub.
> 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by vivek-bala** [comment] 2015-02-04 17:38
Closing as it hasn't been possible to reproduce this. Might have been something temporary on the system.

**Closed by vivek-bala** 2015-02-04 17:38 UTC
